AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ImageUri:
    Type: String
    Default: 822961100047.dkr.ecr.ap-southeast-2.amazonaws.com/sync-redis:latest
  VpcId:
    Type: String
    Default: vpc-0d007b7ab9400c3cc
  SubnetId01:
    Type: String
    Default: subnet-0441d3ad977962ce7
  SubnetId02:
    Type: String
    Default: subnet-058b31fd00981b39c
  # RegisSgId:
  #   Type: string
  #   Default: sg-0d0a6f563b79f76f1

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: gym-junkie-lambda-sync-redis-sg
      GroupDescription: security group for gym-junkie-sync-redis lambda
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          DestinationSecurityGroupId: sg-0d0a6f563b79f76f1
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          DestinationSecurityGroupId: sg-0c708f92f13ca0eb0
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: gym-junkie-sync-redis
      PackageType: Image
      Code:
        ImageUri: !Ref ImageUri
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 5
      MemorySize: 128
      Architectures:
        - arm64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Environment:
        Variables:
          ENVIRONMENT: prod
          SERVER_ADDRESS: https://gymjunkie.moates.com.au
          SERVER_PORT: 443
          DATABASE: gym_tracker
          EMAIL: gymtrackeraus@gmail.com
          REDIS_HOST: gym-junkie-redis-cluster.2q9to2.0001.apse2.cache.amazonaws.com
          REDIS_PORT: 6379
      LoggingConfig:
        LogFormat: JSON
        ApplicationLogLevel: INFO
        SystemLogLevel: INFO

  

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
  
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref LambdaFunction
  
  ExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn