AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Cluster and Service Deployment

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-0d007b7ab9400c3cc
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-0441d3ad977962ce7,subnet-008a9ab8e2df8d977'
  NLBTargetGroupArn:
    Type: String
    Default: arn:aws:elasticloadbalancing:ap-southeast-2:822961100047:targetgroup/gym-junkie-nlb-target-group/d96ebce86394ca7f
  TaskExecutionRoleArn:
    Type: String
    Default: arn:aws:iam::822961100047:role/ecsTaskExecutionRole2
  TaskRoleArn:
    Type: String
    Default: arn:aws:iam::822961100047:role/ecsTaskRole
  EcsServiceRoleArn:
    Type: String
    Default: arn:aws:iam::822961100047:role/ecsServiceRole
  ApiImageUri:
    Type: String
    Default: 822961100047.dkr.ecr.ap-southeast-2.amazonaws.com/gym-junkie
  RedisImageUri:
    Type: String
    Default: 822961100047.dkr.ecr.ap-southeast-2.amazonaws.com/redis
  AppCpu:
    Type: Number
    Default: 256
  AppMemory:
    Type: Number
    Default: 512
  ApiSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-01af9e75214044fc2
  RedisSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-070a1750e31134c77
  ServiceRegistryArn:
    Type: String
    Default: arn:aws:servicediscovery:ap-southeast-2:822961100047:service/srv-dtkzwmvohqnvhlma

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: gym-junkie-cluster-2

  ApiTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: 'gym-junkie-api-task-def'
      Cpu: !Ref AppCpu
      Memory: !Ref AppMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: gym-junkie-api
          Image: !Ref ApiImageUri
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          # LogConfiguration:
          #   LogDriver: awslogs
          #   Options:
          #     awslogs-group: !Ref LogGroup
          #     awslogs-region: !Ref AWS::Region
          #     awslogs-stream-prefix: ecs

  RedisTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: 'gym-junkie-redis-task-def'
      Cpu: !Ref AppCpu
      Memory: !Ref AppMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: gym-junkie-redis
          Image: !Ref RedisImageUri
          PortMappings:
            - ContainerPort: 6379
              Protocol: tcp

  # # --- 3. CloudWatch Log Group ---
  # LogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub '/ecs/gym-junkie-api-${AWS::StackName}'
  #     RetentionInDays: 7 # Adjust as needed

  ApiEcsService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: 'api'
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ApiTaskDef
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref PrivateSubnets
          SecurityGroups:
            - !Ref ApiSecurityGroupId
      LoadBalancers:
        - ContainerName: gym-junkie-api
          ContainerPort: 80
          TargetGroupArn: !Ref NLBTargetGroupArn

  RedisEcsService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: 'redis'
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref RedisTaskDef
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref PrivateSubnets
          SecurityGroups:
            - !Ref RedisSecurityGroupId
      ServiceRegistries:
        - RegistryArn: !Ref ServiceRegistryArn
          ContainerName: gym-junkie-redis

# Outputs:
#   ECSClusterName:
#     Description: The Name of the created ECS Cluster
#     Value: !Ref ECSCluster
#   ECSTaskDefinitionArn:
#     Description: The ARN of the created Task Definition
#     Value: !Ref TaskDefinition