AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Network Load Balancer with TLS Termination on 443'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-0d007b7ab9400c3cc
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-0441d3ad977962ce7,subnet-008a9ab8e2df8d977'

Resources:
  GymJunkieNLBTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: gym-junkie-nlb-target-group
      VpcId: !Ref VpcId
      Protocol: TCP
      Port: 80
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  GymJunkieNLB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: gym-junkie-nlb-2
      Type: network
      Scheme: internet-facing
      Subnets: !Ref SubnetIds

  TLSListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref GymJunkieNLB
      Port: 443
      Protocol: TLS
      Certificates:
        - CertificateArn: arn:aws:acm:ap-southeast-2:822961100047:certificate/dcc73684-264a-4dd9-bdfc-1c4abd33337b
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref GymJunkieNLBTargetGroup