AWSTemplateFormatVersion: '2010-09-09'
Description: 'read only access to s3 bucket'

Parameters:
  BucketName:
    Type: String
    Default: gym-junkie

Resources:
  MyManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: gym-junkie-s3-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:ListBucket
            Resource: !Sub 'arn:aws:s3:::${BucketName}'
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
            Resource: !Sub 'arn:aws:s3:::${BucketName}/*'