AWSTemplateFormatVersion: '2010-09-09'
Description: 'get secret value on secrets'

Parameters:
  PostgresSecretArn:
    Type: String
    Default: arn:aws:secretsmanager:ap-southeast-2:822961100047:secret:prod/gym-junkie/postgres-kQtGJc
  ApiSecretArn:
    Type: String
    Default: arn:aws:secretsmanager:ap-southeast-2:822961100047:secret:prod/gym-junkie/api-SWmGeE

Resources:
  SecretsManagerReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: gym-junkie-secret-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref PostgresSecretArn
              - !Ref ApiSecretArn